# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logmessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10logmessage.proto"X\n\nLogMessage\x12\x1c\n\tlog_level\x18\x01 \x02(\x0e\x32\t.LogLevel\x12\x0e\n\x06logger\x18\x02 \x02(\t\x12\x0b\n\x03mac\x18\x03 \x02(\x0c\x12\x0f\n\x07message\x18\x04 \x01(\t*7\n\x08LogLevel\x12\t\n\x05\x44\x45\x42UG\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\t\n\x05\x45RROR\x10\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "logmessage_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _LOGLEVEL._serialized_start = 110
    _LOGLEVEL._serialized_end = 165
    _LOGMESSAGE._serialized_start = 20
    _LOGMESSAGE._serialized_end = 108
# @@protoc_insertion_point(module_scope)
